apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_CFG_NODE_ID: "0"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka-0.kafka-service:9094"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9093,CONTROLLER://:9094,EXTERNAL://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka-service:9093,EXTERNAL://localhost:9092"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  ALLOW_PLAINTEXT_LISTENER: "yes"
