apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: mlucas4330/orderflow-pro-product-service:v1.0.0
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
