name: Continuous Deployment

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build-and-push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push images
              run: |
                  echo "Building and pushing version ${{ github.ref_name }}"
                  make build-images VERSION=${{ github.ref_name }}
                  make push-images VERSION=${{ github.ref_name }}

    deploy:
        name: Deploy to Production
        runs-on: ubuntu-latest
        needs: build-and-push

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Install Goose
              run: go install github.com/pressly/goose/v3/cmd/goose@latest

            - name: Run Production Migrations
              run: goose -dir "db/migrations" postgres "$POSTGRES_PROD_DSN" up
              env:
                  POSTGRES_PROD_DSN: ${{ secrets.POSTGRES_PROD_DSN }}

            - name: Prepare Kubernetes Manifests
              run: |
                  # Atualiza a tag da imagem em todos os deployments
                  sed -i 's|image: \(.*\):.*|image: ghcr.io/${{ github.repository }}-\1:${{ github.ref_name }}|g' k8s/*-deployment.yml

                  # Cria o ficheiro de segredos a partir do template e dos secrets do GitHub
                  cp k8s/secret.example.yml k8s/secret.prod.yml

                  sed -i "s|POSTGRES_USER:.*|POSTGRES_USER: \"${{ secrets.POSTGRES_USER }}\"|g" k8s/secret.prod.yml
                  sed -i "s|POSTGRES_PASSWORD:.*|POSTGRES_PASSWORD: \"${{ secrets.POSTGRES_PASS }}\"|g" k8s/secret.prod.yml
                  sed -i "s|RABBITMQ_USER:.*|RABBITMQ_USER: \"${{ secrets.RABBITMQ_USER }}\"|g" k8s/secret.prod.yml
                  sed -i "s|RABBITMQ_PASS:.*|RABBITMQ_PASS: \"${{ secrets.RABBITMQ_PASS }}\"|g" k8s/secret.prod.yml
                  sed -i "s|JWT_SECRET_KEY:.*|JWT_SECRET_KEY: \"${{ secrets.JWT_SECRET_KEY }}\"|g" k8s/secret.prod.yml

            - name: Apply Kubernetes Manifests
              run: |
                  kubectl apply -f k8s/secret.prod.yml
                  # Aplica todos os outros manifestos da pasta k8s
                  kubectl apply -f k8s/
